### PR TITLE
from beta to GA

### PR DESCRIPTION
**Pull request by suzutatsu**
for https://github.com/GoogleCloudPlatform/cloud-builders/pull/348

### CODE REVIEW

**Comment by suzutatsu** [comment]
Merged https://github.com/GoogleCloudPlatform/cloud-builders/pull/456

**Comment by mickybart** [comment]
Hold on on this one. I will rebase the PR on top of all changes to clean up it and fix the conflict. The history will be clean.
I will try to work on it today.

**Comment by mickybart** [comment]
Hi @suzutatsu ,

I rebased the code so the history is clean now.
Your 2 commits "from beta to GA" are merged together (with removing api v1).

It is not yet possible to build the docker image for kubectl due to this commit : 3d11322abd7d5d185414eeae5ee0ee9c38b7f58f
I don't catch this commit because that can't work at all as the entrypoint is gcloud !

I will dig on it but I pushed the proper code to permit you to be up to date too.

**Comment by mickybart** [comment]
I pushed a fix for the docker build.
I will give it a try right now in a real context

**Comment by mickybart** [comment]
tested with success on my side. I will update the main PR

**Comment by suzutatsu** [comment]
Thanks.

**Pull request closed without merging**
